name: SCA Analysis with Dependency-Check

on:
  push:
  workflow_dispatch:

jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Dependency-Check
        run: |
          curl -Lo dependency-check-cli.zip https://github.com/jeremylong/DependencyCheck/releases/download/v6.0.4/dependency-check-6.0.4-release.zip
          unzip dependency-check-cli.zip
          ./dependency-check/bin/dependency-check.sh --scan ./ --out dependency-check-report

      - name: Fail if high, critical or medium vulnerabilities in SCA
        run: |
          critical_vulns=$(jq '.dependencies | map(select(.vulnerabilities | length > 0))' dependency-check-report/dependency-check-report.json)
          if [ "$(echo "$critical_vulns" | jq length)" -gt 0 ]; then
            echo "Found high, critical or medium vulnerabilities in SCA. Failing the build."
            exit 1
          else
            echo "No high/critical/medium vulnerabilities found in SCA."
          fi
