name: SCA Analysis with Dependency-Check

on:
  push:
  workflow_dispatch:

jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install Java (needed for Dependency-Check)
        run: sudo apt-get install openjdk-11-jdk -y

      - name: Download and Install Dependency-Check
        run: |
          curl -Lo dependency-check-cli.zip https://github.com/jeremylong/DependencyCheck/releases/download/v7.0.2/dependency-check-7.0.2-release.zip
          unzip -q dependency-check-cli.zip
          chmod +x ./dependency-check/bin/dependency-check.sh

      - name: Run Dependency-Check
        run: |
          ./dependency-check/bin/dependency-check.sh --scan ./ --out dependency-check-report --disableAssemblyAnalyzer

      - name: Check for vulnerabilities
        run: |
          critical_vulns=$(jq '.dependencies | map(select(.vulnerabilities | length > 0))' dependency-check-report/dependency-check-report.json)
          if [ "$(echo "$critical_vulns" | jq length)" -gt 0 ]; then
            echo "Found critical/high/medium vulnerabilities in dependencies. Failing the build."
            exit 1
          else
            echo "No critical/high/medium vulnerabilities found in dependencies."
          fi
